apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-nextjs-service
spec:
  selector:
    app: nextjs
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
