replicaCount: 2
image:
  repository: your-docker-registry/nextjs-app
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: true
  host: nextjs-app.local
  path: /
